name: ðŸš€ Feature Request
description: Suggest a feature for EVA DB
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ðŸ™ Thanks for submitting a EVA DB Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        ðŸ” Please search the [issues](https://github.com/georgia-tech-db/eva/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: ðŸ’¡ A short description of your feature.
      placeholder: |
        What new feature would you like to see in EVA DB?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        ðŸ“ Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: ðŸ“ Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional)  Please consider submitting a [Pull Request](https://github.com/georgia-tech-db/eva/pulls) (PR) to help improve EVA DB for everyone, especially if you have a good understanding of how to implement a fix or feature.
        Please see our âœ… [Contributing Guide](https://github.com/georgia-tech-db/eva/pulls) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
