# coding=utf-8
# Copyright 2018-2023 EvaDB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import os

import pandas as pd
from retry import retry

from evadb.catalog.catalog_type import NdArrayType
from evadb.functions.abstract.abstract_function import AbstractFunction
from evadb.functions.decorators.decorators import forward, setup
from evadb.functions.decorators.io_descriptors.data_types import PandasDataframe
from evadb.utils.generic_utils import try_to_import_gemini

_VALID_CHAT_COMPLETION_MODEL = [
    "gemini-pro",
]


class Gemini(AbstractFunction):
    """
    Arguments:
        model (str) : ID of the Gemini model to use. Refer to '_VALID_CHAT_COMPLETION_MODEL' for a list of supported models.
        temperature (float) : Sampling temperature to use in the model. Higher value results in a more random output.

    Input Signatures:
        query (str)   : The task / question that the user wants the model to accomplish / respond.
        content (str) : Any relevant context that the model can use to complete its tasks and generate the response.

    Output Signatures:
        response (str) : Contains the response generated by the model based on user input. Any errors encountered
                         will also be passed in the response.

    Example Usage:
        Assume we have the transcripts for a few videos stored in a table 'video_transcripts' in a column named 'text'.
        If the user wants to retrieve the summary of each video, the Gemini function can be used as:

            query = "Generate the summary of the video"
            cursor.table("video_transcripts").select(f"Gemini({query}, text)")

        In the above function invocation, the 'query' passed would be the user task to generate video summaries, and the
        'content' passed would be the video transcripts that need to be used in order to generate the summary. Since
        no prompt is passed, the default system prompt will be used.

        Now assume the user wants to create the video summary in 50 words and in French. Instead of passing these instructions
        along with each query, a prompt can be set as such:

            prompt = "Generate your responses in 50 words or less. Also, generate the response in French."
            cursor.table("video_transcripts").select(f"Gemini({query}, text, {prompt})")

        In the above invocation, an additional argument is passed as prompt. While the query and content arguments remain
        the same, the 'prompt' argument will be set as a system message in model params.

        Both of the above cases would generate a summary for each row / video transcript of the table in the response.
    """

    @property
    def name(self) -> str:
        return "Gemini"

    @setup(cacheable=True, function_type="chat-completion", batchable=True)
    def setup(
        self,
        model="gemini-pro",
        temperature: float = 0,
        gemini_api_key="",
    ) -> None:
        assert model in _VALID_CHAT_COMPLETION_MODEL, f"Unsupported Gemini {model}"
        self.model = model
        self.temperature = temperature
        self.gemini_api_key = gemini_api_key

    @forward(
        input_signatures=[
            PandasDataframe(
                columns=["query", "content"],
                column_types=[
                    NdArrayType.STR,
                    NdArrayType.STR,
                ],
                column_shapes=[(1,), (1,)],
            )
        ],
        output_signatures=[
            PandasDataframe(
                columns=["response"],
                column_types=[
                    NdArrayType.STR,
                ],
                column_shapes=[(1,)],
            )
        ],
    )
    def forward(self, text_df):
        try_to_import_gemini()
        import google.generativeai as genai

        api_key = self.gemini_api_key
        if len(self.gemini_api_key) == 0:
            api_key = os.environ.get("GEMINI_API_KEY", "")
        assert (
            len(api_key) != 0
        ), "Please set your API key using SET GEMINI_API_KEY = '' or environment variable (GEMINI_API_KEY)"

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(self.model)

        @retry(tries=6, delay=20)
        def completion_with_backoff(content):
            return model.generate_content(
                content, generation_config={"temperature": self.temperature}
            )

        queries = text_df[text_df.columns[0]]
        content = text_df[text_df.columns[0]]
        if len(text_df.columns) > 1:
            queries = text_df.iloc[:, 0]
            content = text_df.iloc[:, 1]

        results = []
        for query, content in zip(queries, content):
            message = f"Here is some context: {content}\n. Now, complete the following task: {query}"

            response = completion_with_backoff(message)
            if len(response.parts) > 0:
                results.append(response.text)
            assert (
                len(response.parts) != 0
            ), "Gemini could not generate content for this prompt."

        df = pd.DataFrame({"response": results})

        return df
