# -*- coding: utf-8 -*-
import os
import sys
import warnings
from datetime import date

sys.path.insert(0, os.path.abspath(".."))

import themes.sphinx_scylladb_theme

# -- Global variables

# Build documentation for the following tags and branches
TAGS = []
BRANCHES = []

# Set which versions are not released yet.
UNSTABLE_VERSIONS = ["master"]
# Set which versions are deprecated
DEPRECATED_VERSIONS = [""]

# The full version, including alpha/beta/rc tags
VERSION_DICT = {}
with open("../../eva/version.py", "r") as version_file:
    exec(version_file.read(), VERSION_DICT)

# Set the latest version.
LATEST_VERSION = VERSION_DICT["VERSION"]

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "sphinx.ext.extlinks",
    "sphinx_sitemap",
    "sphinx_multiversion",  # optional
    "recommonmark",  # optional
]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "EVA Video Database System"
copyright = str(date.today().year) + ", Georgia Tech Database Group."
author = u"Georgia Tech Database Group"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# List of substitutions
rst_prolog = """
.. |rst| replace:: restructuredText
"""
# -- Options for not found extension ---------------------------------------

# Template used to render the 404.html generated by this extension.
notfound_template = "404.html"

# Prefix added to all the URLs generated in the 404 page.
notfound_urls_prefix = ""

# -- Options for sitemap extension ---------------------------------------

sitemap_url_scheme = "stable/{link}"

# -- Options for multiversion extension ----------------------------------


def multiversion_regex_builder(versions):
    """Generates a regex string from a list of versions.
    Every documentation project `conf.py` file uses this function
    to define the different documentation versions supported.
    :param versions: A list of versions. Versions could be either branch names or tags.
    :type versions: list of str
    :return: The equivalent regular expression.
    :rtype: str
    """

    if len(versions) == 0:
        return "None"
    elif len(versions) == 1 and versions[0] == "*":
        return r"^.*"
    elif len(versions) == 1:
        return r"^" + versions[0] + r"$"
    else:
        return r"\b(" + "|".join(versions) + r")\b"

# Whitelist pattern for tags
smv_tag_whitelist = multiversion_regex_builder(TAGS)
# Whitelist pattern for branches
smv_branch_whitelist = multiversion_regex_builder(BRANCHES)
# Defines which version is considered to be the latest stable version.
smv_latest_version = LATEST_VERSION
# Defines the new name for the latest version.
smv_rename_latest_version = "stable"
# Whitelist pattern for remotes (set to None to use local branches only)
smv_remote_whitelist = r"^origin$"
# Pattern for released versions
smv_released_pattern = r"^tags/.*$"
# Format for versioned output directories inside the build directory
smv_outputdir_format = "{ref.name}"

# -- Options for HTML output ----------------------------------------------

# The theme to use for pages.
html_theme = "sphinx_scylladb_theme"
html_theme_path = ["themes"]


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for the theme, see the
# documentation.
html_theme_options = {
    "conf_py_path": "docs/api/",
    "hide_edit_this_page_button": "false",
    "hide_banner": "false",
    "github_issues_repository": "georgia-tech-db/eva",
    "github_repository": "georgia-tech-db/eva",
    "site_description": "EVA Video Database System",
    "hide_version_dropdown": ["master"],
    "versions_unstable": UNSTABLE_VERSIONS,
    "versions_deprecated": DEPRECATED_VERSIONS,
    "banner_button_text": '',
    "banner_button_url": '',
    "banner_icon_path": '_static/mascots/Logo.png',
    "banner_title_text": '',
    "hide_banner": 'true',
    "navigation_depth": -1
}

# Last updated format
html_last_updated_fmt = "%d %b %Y"

# Custom sidebar templates, maps document names to template names.
html_sidebars = {"**": ["side-nav.html"]}

# Output file base name for HTML help builder.
htmlhelp_basename = "ScyllaDocumentationdoc"

# URL which points to the root of the HTML documentation.
html_baseurl = "https://evadb.readthedocs.io"

# Dictionary of values to pass into the template engine’s context for all pages
html_context = {"html_baseurl": html_baseurl}

# -- Initialize Sphinx ----------------------------------------------
def setup(sphinx):
    warnings.filterwarnings(
        action="ignore",
        category=UserWarning,
        message=r".*Container node skipped.*",
    )

    themes.sphinx_scylladb_theme.setup(sphinx)

